spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/edude?characterEncoding=utf8&servrTimezone=Asia/Shanghai
      username: root
      password: v8~21txcq
      max-active: 20
      max-wait: 6000
      min-idle: 1
      test-on-borrow: true
      test-on-return: true
  thymeleaf:
    mode: HTML5
mybatis:
  mapper-locations: classpath*:com/aresix/eudemoniabackend/mapper/*Mapper.xml
  config-location: classpath:mybatis-config.xml
